version: '2'
services:
  bu-transaction:
    container_name: bu-transaction
    image: node:9
    volumes:
      - ./:/app/
      - .env.docker:/app/.env
    ports:
      - "9001"
    entrypoint: /bin/sh
    command: -c "sleep 5 && cd /app/ && yarn && yarn start:dev"
    networks:
      - evolve
networks:
  evolve:
    external: true
